// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package options

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson24099d24DecodeGithubComK1nkyTookhookPluginTelegramInternalOptions(in *jlexer.Lexer, out *PluginOptions) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "chat":
			out.Chat = string(in.String())
		case "token":
			out.Token = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson24099d24EncodeGithubComK1nkyTookhookPluginTelegramInternalOptions(out *jwriter.Writer, in PluginOptions) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"chat\":"
		out.RawString(prefix[1:])
		out.String(string(in.Chat))
	}
	{
		const prefix string = ",\"token\":"
		out.RawString(prefix)
		out.String(string(in.Token))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PluginOptions) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson24099d24EncodeGithubComK1nkyTookhookPluginTelegramInternalOptions(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PluginOptions) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson24099d24EncodeGithubComK1nkyTookhookPluginTelegramInternalOptions(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PluginOptions) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson24099d24DecodeGithubComK1nkyTookhookPluginTelegramInternalOptions(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PluginOptions) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson24099d24DecodeGithubComK1nkyTookhookPluginTelegramInternalOptions(l, v)
}
